sudo: false
language: go
go:
  - 1.8
  - tip
services:
  - docker
  - mysql
env:
  global:
    - PATH=/home/travis/gopath/bin:$PATH
    - secure: cHU+9fjOOdeb3dE7X/EhcsGfzQ+Uxi+Gl03jAZTZqHCVB94mlgmPaOQb6GimOdZwSstbBTkfpcqToF7k631Y55G+fElO0iuvgW2ivkblO5G5M4UBzP+eJ/bnnYZsWlBz91nPskv863DJ2ou5wMeVeYzbtk+Ri5bG+N2tgRocguHyC8XYPJhWq6J8mq+JeXGoLIrUkeZVBPLzW/ED6eJBmidMG6R7ozMwfoyi5uvOruUUTmVIY7SjWKROgn/F9EKhnrV8oZxP8sQqG+5BANKFcHc74ubK1FNJj3MJyL8NmZAseJxdpy5XUD5gQLlRuHQIsAsr+diJSgPqVrB8Iv0ig82qg/6TgUY5keRpP1W9HU2kNFpCBPUdZRH1no6eGBJD/jOLHLC6L+tuTfZGBbJaTT9qRHGaPJetJeqjKXOOK0W4br9uQ0XNRSJs7IHTzrLUaia67QaAF0D5h0arYdtBvqnHwg0MyA574jV7MhvX6APqSIw9nj+i0aa/5W8G8sQRT+CsOU6TtNYJWVSQPO7NE38beyf/tamfywLVzvb8lwHxThibxoTNYQ1i7N3kyqFewLOWxuUkLPN3LsE5Qv+ZIDM1VP6DVlkiDogx5CTnF0NRvlY6vrTBGe04ufPpkRHb4F3KsMoGx0r+bUs/LBjQOGT0aviNc8PcgyAvwSpOYcs=
    - COMMIT=${TRAVIS_COMMIT::8

before_install:
  - go get -u -t -v ./...
  - go get github.com/golang/lint/golint
  - go get github.com/mitchellh/gox
  - mysql -e 'CREATE DATABASE Chores;'

script:
  - go vet $(go list ./... | grep -v vendor)
  - go test $(go list ./... | grep -v '/vendor/')
  - gox -ldflags "-X main.Version=$TRAVIS_BUILD_NUMBER" -output "chores_{{.OS}}_{{.Arch}}" -osarch="linux/amd64"

after_success:
  - docker login -u benschw -p $DOCKER_PASS
  - export REPO=benschw/chores
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
